/**
 * 静态的 Mock 数据，方便开发的时候使用。
 * 关于此配置项的功能细节，请参考 base-url-config.ts 中的注释。
 */
export const dataURL = {
    postListURL: "mock-data/post-list-mock.json",
    postDetailURL: "mock-data/post-detail-mock.json",
    postTableURL: "mock-data/post-table-mock.json",
    delPostURL: "",
    capchaURL: "",
    signInURL: "mock-data/user-login-mock.json",
    signOutURL: "mock-data/user-login-mock.json",
    getSessionUserURL: "",
    testEmailURL: "",
    signUpURL: "mock-data/user-register-mock.json",
    commentListURL: "mock-data/comment-list-mock.json",
    delCommentURL: "",
    userListURL: "mock-data/user-list-mock.json",
    userDetailURL: "mock-data/user-detail-mock.json",
    updateUserURL: "mock-data/user-register-mock.json",
    delUserURL: "",
    userMenuListURL: "mock-data/user-menu-list-mock.json",  //用户对应的菜单
    roleTableURL: "mock-data/role-list-mock.json",
    roleListByUserIdURL: "mock-data/role-list-mock.json",
    updateUserRoleRelationURL: "",
    roleDetailURL: "mock-data/role-detail-mock.json",
    delRoleURL: "",
    newRoleURL: "",
    updateRoleURL: "",
    apiPermissionTableURL: "mock-data/api-permission-list-mock.json",
    apiPermissionListAll: "mock-data/api-permission-list-all-mock.json",
    apiPermissionListAllByRole: "mock-data/api-permission-list-by-role-mock.json",
    apiPermissionDetailURL: "mock-data/api-permission-detail-mock.json",
    delApiPermissionURL: "",
    newApiPermissionURL: "",
    updateApiPermissionURL: "",
    apiRoleListURL: "mock-data/api-role-list-mock.json",
    compPermListURL: "mock-data/component-permission-list.json",
    compPermissionListAllByRole: "mock-data/component-permission-list-by-role-mock.json",
    compPermDetailURL: "mock-data/component-permission-detail-mock.json",
    delCompPermURL: "",
    newCompPermURL: "",
    updateCompPermURL: "",
    compRoleListURL: "",
    sendEmailURL: "mock-data/forget-pwd-mock.json",
    getSysParamsURL: "mock-data/sys-params-mock.json",
    commentListByPostIdURL: "mock-data/comment-list-mock.json",
    writeCommentURL: "",
};